version: '3.8'
services:
  db-auth:
    image: postgres:15
    container_name: db-auth
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER_AUTH}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_AUTH}"
      POSTGRES_DB: "${POSTGRES_DB_AUTH}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  db-room:
    image: postgres:15
    container_name: db-room
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER_ROOM}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_ROOM}"
      POSTGRES_DB: "${POSTGRES_DB_ROOM}"
    ports:
      - "5433:5432"
    volumes:
      - postgres_room_data:/var/lib/postgresql/data
      
  auth-service:
    build: ./auth-service
    ports:
      - "5002:5002"
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db-auth
    networks:
      - backend

  rooms-service:
    build: ./rooms-service
    ports:
      - "5003:5003"
    volumes:
      - ./rooms-service:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    ports:
      - "5001:5001"
    volumes:
      - ./api-gateway:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - backend
    depends_on:
      - auth-service
      - rooms-service

volumes:
  postgres_auth_data:
  postgres_room_data:

networks:
  backend:
    driver: bridge
