"""empty message

Revision ID: 506fd666ca98
Revises: 
Create Date: 2025-03-10 11:25:42.713134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506fd666ca98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('access_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_lists')
    op.drop_table('rooms')
    # ### end Alembic commands ###
