"""Initial migration.

<<<<<<<< HEAD:auth-service/migrations/versions/d91b6d450039_.py
Revision ID: d91b6d450039
Revises: 
Create Date: 2025-03-06 19:41:40.457246
========
Revision ID: b6fc669efbd2
Revises: 
Create Date: 2025-03-05 16:38:29.239583
>>>>>>>> 093ac90 (feat(auth): implement user authentication with sign-up and sign-in endpoints):auth-service/migrations/versions/b6fc669efbd2_initial_migration.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:auth-service/migrations/versions/d91b6d450039_.py
revision = 'd91b6d450039'
========
revision = 'b6fc669efbd2'
>>>>>>>> 093ac90 (feat(auth): implement user authentication with sign-up and sign-in endpoints):auth-service/migrations/versions/b6fc669efbd2_initial_migration.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
